sudo: required

language: c

services:
  - docker

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1
  - git clone https://github.com/intel/linux-sgx.git -b sgx_2.1.3 --depth=1

script:
  - >
    docker run -v $PWD:/app -w /app reznik/gnat:gpl.2018.slim /bin/bash -c
    "apt-get update && apt-get install -y build-essential ocaml automake autoconf libtool wget python libssl-dev
    && cd linux-sgx
    && sed -i '0,/^/s//long syscall(int, ...);/' sdk/gperftools/gperftools-2.5/src/base/logging.h
    && ./download_prebuilt.sh
    && cd sdk
    && make
    && cd ..
    && make sdk_install_pkg
    && echo -e 'no\n/opt/intel\n' | ./linux/installer/bin/sgx_linux_x64_sdk_2.1.3.44322.bin
    && source /opt/intel/sgxsdk/environment
    && cd /app
    && make SGX_MODE=SIM
    && ./app"
